### PR TITLE
Remove ruby-xslt dependency

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- #21

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
@opoudjis could you please help me to understand: we use `match_fuzzy` but still it cares about `\n` (I have changed expected test output just added `\n`)

Maybe I did it wrong way and we ca supply extra param to `match_fuzzy` and it will ignore `\n`?

**Comment by opoudjis** [comment]
lib/html2doc/mathml2omml.xsl, which you deleted, is the official Microsoft XSLT; the file actually used is an earlier draft of the XSLT, which is therefore (presumably!) not subject to redistribution constraints; it was in fact redistributed by TEI. Deleting it is fine, it was a just-in-case.

**Comment by CAMOBAP795** [comment]
@opoudjis thanks for note, anyway it will be in git history

**Comment by opoudjis** [comment]
https://github.com/winebarrel/rspec-match_fuzzy/blob/master/lib/rspec/match_fuzzy.rb : match fuzzy does not ignore `\n` completely, it just substitutes multiple consecutive `\n` with a single `\n`, and strips final `\n`. Your include modification has added `\n` between each element; that's fine, but it also isn't ignored by match_fuzzy. In any case, don't worry about it, it's fine.

**Pull request merged**
