### PR TITLE
#55 use nokogiri ~> 1.10

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Comment by CAMOBAP** [comment]
hmm, interesting failure I will have a look

**Comment by ronaldtse** [comment]
Here's the failure. This is a behavioural difference:

```xml
 <div><m:oMath>
-<m:nary><m:naryPr><m:chr m:val="&#x2211;"></m:chr><m:limLoc m:val="undOvr"></m:limLoc><m:grow m:val="on"></m:grow><m:subHide m:val="off"></m:subHide><m:supHide m:val="off"></m:supHide></m:naryPr><m:sub><m:r><m:t>i=1</m:t></m:r></m:sub><m:sup><m:r><m:t>n</m:t></m:r></m:sup><m:e><m:sSup><m:e><m:r><m:t>i</m:t></m:r></m:e><m:sup><m:r><m:t>3</m:t></m:r></m:sup></m:sSup></m:e></m:nary><span style="font-style:normal;"><m:r><m:rPr><m:sty m:val="p"></m:sty></m:rPr><m:t>=</m:t></m:r></span><m:sSup><m:e><m:d><m:dPr><m:sepChr m:val=","></m:sepChr></m:dPr><m:e><m:f><m:fPr><m:type m:val="bar"></m:type></m:fPr><m:num><m:r><m:t>n</m:t></m:r><m:d><m:dPr><m:sepChr m:val=","></m:sepChr></m:dPr><m:e><m:r><m:t>n+1</m:t></m:r></m:e></m:d></m:num><m:den><m:r><m:t>2</m:t></m:r></m:den></m:f></m:e></m:d></m:e><m:sup><m:r><m:t>2</m:t></m:r></m:sup></m:sSup><m:r><m:rPr><m:nor></m:nor></m:rPr><m:t>"integer"</m:t></m:r><span style="font-style:normal;"><m:r><m:rPr><m:sty m:val="p"></m:sty></m:rPr><m:t>)</m:t></m:r></span>
+<m:nary><m:naryPr><m:chr m:val="&#x2211;"></m:chr><m:limLoc m:val="undOvr"></m:limLoc><m:grow m:val="on"></m:grow><m:subHide m:val="off"></m:subHide><m:supHide m:val="off"></m:supHide></m:naryPr><m:sub><m:r><m:t>i=1</m:t></m:r></m:sub><m:sup><m:r><m:t>n</m:t></m:r></m:sup><m:e><m:sSup><m:e><m:r><m:t>i</m:t></m:r></m:e><m:sup><m:r><m:t>3</m:t></m:r></m:sup></m:sSup></m:e></m:nary><m:span style="font-style:normal;"><m:r><m:rPr><m:sty m:val="p"></m:sty></m:rPr><m:t>=</m:t></m:r></m:span><m:sSup><m:e><m:d><m:dPr><m:sepChr m:val=","></m:sepChr></m:dPr><m:e><m:f><m:fPr><m:type m:val="bar"></m:type></m:fPr><m:num><m:r><m:t>n</m:t></m:r><m:d><m:dPr><m:sepChr m:val=","></m:sepChr></m:dPr><m:e><m:r><m:t>n+1</m:t></m:r></m:e></m:d></m:num><m:den><m:r><m:t>2</m:t></m:r></m:den></m:f></m:e></m:d></m:e><m:sup><m:r><m:t>2</m:t></m:r></m:sup></m:sSup><m:r><m:rPr><m:nor></m:nor></m:rPr><m:t>"integer"</m:t></m:r><m:span style="font-style:normal;"><m:r><m:rPr><m:sty m:val="p"></m:sty></m:rPr><m:t>)</m:t></m:r></m:span>
 </m:oMath>
 </div>
```

### Formatted

Expected (Nokogiri 1.10):
```xml
<m:nary>
	<m:naryPr>
		<m:chr m:val="&#x2211;"></m:chr>
		<m:limLoc m:val="undOvr"></m:limLoc>
		<m:grow m:val="on"></m:grow>
		<m:subHide m:val="off"></m:subHide>
		<m:supHide m:val="off"></m:supHide>
	</m:naryPr>
	<m:sub>
		<m:r>
			<m:t>i=1</m:t>
		</m:r>
	</m:sub>
	<m:sup>
		<m:r>
			<m:t>n</m:t>
		</m:r>
	</m:sup>
	<m:e>
		<m:sSup>
			<m:e>
				<m:r>
					<m:t>i</m:t>
				</m:r>
			</m:e>
			<m:sup>
				<m:r>
					<m:t>3</m:t>
				</m:r>
			</m:sup>
		</m:sSup>
	</m:e>
</m:nary>
<m:span style="font-style:normal;">
	<m:r>
		<m:rPr>
			<m:sty m:val="p"></m:sty>
		</m:rPr>
		<m:t>=</m:t>
	</m:r>
</m:span>
<m:sSup>
	<m:e>
		<m:d>
			<m:dPr>
				<m:sepChr m:val=","></m:sepChr>
			</m:dPr>
			<m:e>
				<m:f>
					<m:fPr>
						<m:type m:val="bar"></m:type>
					</m:fPr>
					<m:num>
						<m:r>
							<m:t>n</m:t>
						</m:r>
						<m:d>
							<m:dPr>
								<m:sepChr m:val=","></m:sepChr>
							</m:dPr>
							<m:e>
								<m:r>
									<m:t>n+1</m:t>
								</m:r>
							</m:e>
						</m:d>
					</m:num>
					<m:den>
						<m:r>
							<m:t>2</m:t>
						</m:r>
					</m:den>
				</m:f>
			</m:e>
		</m:d>
	</m:e>
	<m:sup>
		<m:r>
			<m:t>2</m:t>
		</m:r>
	</m:sup>
</m:sSup>
<m:r>
	<m:rPr>
		<m:nor></m:nor>
	</m:rPr>
	<m:t>"integer"</m:t>
</m:r>
<m:span style="font-style:normal;">
	<m:r>
		<m:rPr>
			<m:sty m:val="p"></m:sty>
		</m:rPr>
		<m:t>)</m:t>
	</m:r>
</m:span>
```

Now (Nokogiri 1.11):
```xml
<m:nary>
	<m:naryPr>
		<m:chr m:val="&#x2211;"></m:chr>
		<m:limLoc m:val="undOvr"></m:limLoc>
		<m:grow m:val="on"></m:grow>
		<m:subHide m:val="off"></m:subHide>
		<m:supHide m:val="off"></m:supHide>
	</m:naryPr>
	<m:sub>
		<m:r>
			<m:t>i=1</m:t>
		</m:r>
	</m:sub>
	<m:sup>
		<m:r>
			<m:t>n</m:t>
		</m:r>
	</m:sup>
	<m:e>
		<m:sSup>
			<m:e>
				<m:r>
					<m:t>i</m:t>
				</m:r>
			</m:e>
			<m:sup>
				<m:r>
					<m:t>3</m:t>
				</m:r>
			</m:sup>
		</m:sSup>
	</m:e>
</m:nary>
<span style="font-style:normal;">
	<m:r>
		<m:rPr>
			<m:sty m:val="p"></m:sty>
		</m:rPr>
		<m:t>=</m:t>
	</m:r>
</span>
<m:sSup>
	<m:e>
		<m:d>
			<m:dPr>
				<m:sepChr m:val=","></m:sepChr>
			</m:dPr>
			<m:e>
				<m:f>
					<m:fPr>
						<m:type m:val="bar"></m:type>
					</m:fPr>
					<m:num>
						<m:r>
							<m:t>n</m:t>
						</m:r>
						<m:d>
							<m:dPr>
								<m:sepChr m:val=","></m:sepChr>
							</m:dPr>
							<m:e>
								<m:r>
									<m:t>n+1</m:t>
								</m:r>
							</m:e>
						</m:d>
					</m:num>
					<m:den>
						<m:r>
							<m:t>2</m:t>
						</m:r>
					</m:den>
				</m:f>
			</m:e>
		</m:d>
	</m:e>
	<m:sup>
		<m:r>
			<m:t>2</m:t>
		</m:r>
	</m:sup>
</m:sSup>
<m:r>
	<m:rPr>
		<m:nor></m:nor>
	</m:rPr>
	<m:t>"integer"</m:t>
</m:r>
<span style="font-style:normal;">
	<m:r>
		<m:rPr>
			<m:sty m:val="p"></m:sty>
		</m:rPr>
		<m:t>)</m:t>
	</m:r>
</span>
```

The difference is in the tag name -- the previous expectation is `<m:span>`, the new version gives `<span>`.

Expectation:
```xml
<m:span style="font-style:normal;">
```

New:
```xml
<span style="font-style:normal;">
```

**Comment by ronaldtse** [comment]
Discussed with @opoudjis , this is new behavior for Nokogiri 1.11 regarding namespaces.

Course of action:
1. Check if `<span>` breaks Word. If it does, we need to re-insert the prefix to turn that back into `<m:span>`.
2. If it doesn't break Word, we need to update specs.

**Comment by opoudjis** [comment]
Well this is embarrassing.

The Nokogiri 1.11 behaviour is in fact the correct behaviour: the `span` element is HTML, and should *not* have been namespaced with the MathML namespace. The Nokogiri 1.11 behaviour is what is being output correctly in Word. The spec does in fact need to be updated.

**Comment by ronaldtse** [comment]
@opoudjis so does this mean we need to fix the spec/implementation for 1.10 as well?

**Comment by opoudjis** [comment]
Hold on. You've misreported, @ronaldtse, it's the wrong way around:

The `<span>` is correctly not prefixed with the MathML namespace in Nokogiri 1.10. It is in Nokogiri 1.11. That behaviour needs to be prevented.

**Comment by ronaldtse** [comment]
Oh, you might be right here. So the new version needs to be fixed to remove that prefix.

**Pull request merged**
